services:

  database:
    image: postgres
    ports:
      - 5499:5432
    restart: always
    
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=three_ships
